### PR TITLE
Miscellaneous build fixes

### PR DESCRIPTION
**Pull request by arch1t3cht**
Various small fixes to building and installer generation that came up on arch1t3cht/Aegisub .

The two most "controversial" commits are at the bottom:
- Avisynth is broken anyway (at least for now), so the paths could also just be taken out
- The commit that adds bundling of the hunspell dictionaries downloads them from Sourceforge (mainly to document where they came from), but that download fails quite frequently on the CI. So maybe it's better to just check them into the repo or use some newer dictionary.

### CODE REVIEW

**Comment by arch1t3cht** [comment]
They're around 250KB and weren't updated since... 2007.

**Comment by CoffeeFlux** [comment]
That's pretty bad. Are they hosted anywhere else we could use as a fallback?

**Comment by arch1t3cht** [comment]
I don't think so, they're pretty old after all and most applications just use SCOWL nowadays.

**Comment by arch1t3cht** [comment]
Yeah, done.

**Pull request merged**
