### PR TITLE
Meson dependency check fixes

### PR DESCRIPTION
**Pull request by astiob**

### CODE REVIEW

**Comment by CoffeeFlux** [comment]
It's possible that Windows CI will fail due to the issue with the libass port, just as a heads-up. I really need to go fix that :(

**Review by CoffeeFlux — APPROVED** [review]
This last commit seems slightly suspect to me - if `dependency('openal')` is searching for the wrong string and unable to locate the correct version, that's probably something that needs to be addressed at the Meson level? But if this gets things working I'm fine to merge and I can go file a report with them later.

**Comment by CoffeeFlux** [comment]
Also, thanks for this! I don't use my Mac much so this hasn't been as well tested as Windows or Linux, so I really appreciate you giving it a spin on an older machine.

**Comment by astiob** [comment]
> This last commit seems slightly suspect to me - if `dependency('openal')` is searching for the wrong string and unable to locate the correct version, that's probably something that needs to be addressed at the Meson level?

The main problem here is the version constraint, which Meson obediently tries to enforce but the framework doesn’t satisfy. `git blame` tells me this version check has been present from the very first Aegisub commit that introduced OpenAL support, which aimed it at pkg-config-provided OpenAL and didn’t attempt to support the macOS framework at all. I assume the framework doesn’t _have_ a tangible version number (indeed, all I can find is “Versions/A” and “1.0.0”), and even if it did, I doubt it’d be on the same scale as the 0.0.8 constraint for pkg-config.

Honestly, I have no idea which OpenAL library’s versioning it is supposed to match at all and hence whether this version check is correct even on non-macOS. But for what it’s worth in the specific macOS case, the pre-Meson code that later added support for the macOS framework had no version check of any kind, and Aegisub built against the framework works for me on macOS 10.13 and probably previously worked for me in the official build of Aegisub 3.0.4 on 10.6.

Usually, macOS uses case-insensitive file systems, and Meson does find the framework. But macOS does also support case-sensitive file systems, including on the main system partition (unless Apple has taken this option away in the recent years and I’m not aware of it). Meson doesn’t really have a good way to figure out the canonical spelling of the framework name, especially since frameworks can be found in multiple locations, so it just calls the compiler with `-framework foobar`. _Maybe_ the compiler is smart enough to match it case-insensitively even on case-sensitive file systems; I’m afraid I don’t know. But as I was adding code to handle this as a special branch anyway, I figured it’d be safer to ensure the canonical spelling is used.

**Pull request merged**
