### PR TITLE
Fix AppData.xml installation

### LINKED ISSUE #215: Packaging: Lacking of AppData.xml file installation
`packages/meson.build` does not include installation of `aegisub.appdata.xml`, as fixed at [here](https://github.com/arch1t3cht/Aegisub/commit/8c35b1d642285b77cf1b382f47b13f83c4e8938c). Relevant commits could be merged to solve the problem.
Additionally, the metadata should be `aegisub.metainfo.xml`, according to the [specification](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps) change.

### PR DESCRIPTION
**Pull request by EL-File4138**
This fix #215.

It passed an out-of-band build/packaging [session](https://copr.fedorainfracloud.org/coprs/el-file4138/vapoursynth-classic/build/8418826/) on Fedora Copr.

### CODE REVIEW

**Comment by arch1t3cht** [comment]
Could you also cherry-pick the two other desktop/appdata-related commits from https://github.com/arch1t3cht/Aegisub/pull/52/commits and remove the `CherryPick: ` prefix? Then I can merge (once the CI runs through).

**Comment by EL-File4138** [comment]
Did a bit of force push to correct past commit state, hope that does not mess around the history. Also corrected the metadata template.
I think the i18n module is still not working for metadata translation, but to be honest the pot file hasn't been properly updated for years. I think this should be left for a complete i18n update while collaborating on all the new translation efforts. For now, a quick fix as such should suffice.

**Comment by arch1t3cht** [comment]
Your rebase had a merge conflict marker in it that was then again wiped by the first renaming commit, so I re-cherry-picked things and force pushed.

meson's i18n module is definitely still not complete, yes, but that can be fixed some other time.

**Comment by EL-File4138** [comment]
Understood, do you think it's ready to be merged now?

**Pull request merged**
