### PR TITLE
meson: Apply Lua 5.2 compat flags to both native and non-native builds

### PR DESCRIPTION
**Pull request by Myaamori**
This pull request intentionally solves this in the dumbest and ugliest way possible in order to force Ryan to come up with something better (or alternatively conclude that this is actually the way to do it).

### CODE REVIEW

**Comment by Myaamori** [comment]
An alternative approach could be to simply not support cross compilation and drop `native` everywhere (will break if cross compiling to a different platform since `buildvm` needs to be run locally during the build).

**Comment by Myaamori** [comment]
After reading through LuaJIT's Makefile a bit more carefully (as well as running some tests, see below), it turns out that `LUAJIT_OS` is actually only set for `minilua` and `buildvm` (and technically only when cross compiling, though including them even when not cross compiling doesn't seem to result in any issues). 

```
$ HOST_SYS=Linux TARGET_SYS=Windows make 2>/dev/null | grep gcc 
gcc  -O2 -fomit-frame-pointer -Wall -DLUAJIT_ENABLE_LUA52COMPAT  -I. -malign-double -DLUAJIT_OS=LUAJIT_OS_WINDOWS -DLUAJIT_TARGET=LUAJIT_ARCH_x64 -DLJ_ARCH_HASFPU=1 -DLJ_ABI_SOFTFP=0  -c -o host/minilua.o host/minilua.c
gcc     -o host/minilua host/minilua.o -lm   
gcc  -O2 -fomit-frame-pointer -Wall -DLUAJIT_ENABLE_LUA52COMPAT  -I. -malign-double -DLUAJIT_OS=LUAJIT_OS_WINDOWS -DLUAJIT_TARGET=LUAJIT_ARCH_x64 -DLJ_ARCH_HASFPU=1 -DLJ_ABI_SOFTFP=0  -c -o host/buildvm.o host/buildvm.c
gcc  -O2 -fomit-frame-pointer -Wall -DLUAJIT_ENABLE_LUA52COMPAT  -I. -malign-double -DLUAJIT_OS=LUAJIT_OS_WINDOWS -DLUAJIT_TARGET=LUAJIT_ARCH_x64 -DLJ_ARCH_HASFPU=1 -DLJ_ABI_SOFTFP=0  -c -o host/buildvm_asm.o host/buildvm_asm.c
gcc  -O2 -fomit-frame-pointer -Wall -DLUAJIT_ENABLE_LUA52COMPAT  -I. -malign-double -DLUAJIT_OS=LUAJIT_OS_WINDOWS -DLUAJIT_TARGET=LUAJIT_ARCH_x64 -DLJ_ARCH_HASFPU=1 -DLJ_ABI_SOFTFP=0  -c -o host/buildvm_peobj.o host/buildvm_peobj.c
gcc  -O2 -fomit-frame-pointer -Wall -DLUAJIT_ENABLE_LUA52COMPAT  -I. -malign-double -DLUAJIT_OS=LUAJIT_OS_WINDOWS -DLUAJIT_TARGET=LUAJIT_ARCH_x64 -DLJ_ARCH_HASFPU=1 -DLJ_ABI_SOFTFP=0  -c -o host/buildvm_lib.o host/buildvm_lib.c
gcc  -O2 -fomit-frame-pointer -Wall -DLUAJIT_ENABLE_LUA52COMPAT  -I. -malign-double -DLUAJIT_OS=LUAJIT_OS_WINDOWS -DLUAJIT_TARGET=LUAJIT_ARCH_x64 -DLJ_ARCH_HASFPU=1 -DLJ_ABI_SOFTFP=0  -c -o host/buildvm_fold.o host/buildvm_fold.c
gcc     -o host/buildvm host/buildvm.o host/buildvm_asm.o host/buildvm_peobj.o host/buildvm_lib.o host/buildvm_fold.o   
gcc  -O2 -fomit-frame-pointer -Wall -DLUAJIT_ENABLE_LUA52COMPAT  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -U_FORTIFY_SOURCE  -DLUA_MULTILIB=\"lib\" -DLUA_BUILD_AS_DLL   -c -o lj_gc.o lj_gc.c
```

So declaring these arguments only for native builds should have the same effect (see updated pull request). In that case it's only `-DLUAJIT_ENABLE_LUA52COMPAT` that ends up having to be set twice (for both native and host builds). Not sure if it's worth going through the trouble of passing `c_args` everywhere just for one flag?

**Comment by FichteFoll** [comment]
You should proabably add a comment for the almost duplicatd `-DLUAJIT_ENABLE_LUA52COMPAT` line.

**Comment by bebetoalves** [comment]
Thank you Myaamori :D. I spent three days trying to compile, but now I've got it.

**Pull request merged**
